### ISSUE TITLE
Use requests module

### ISSUE THREAD

**Issue by the01** [KurochkinVasiliy/theoldreader#2]
If you were to use the [requests](https://pypi.python.org/pypi/requests) package, you could actually support python 2 alongside python 3

**Comment by the01** [comment]
Initial support at the01/theoldreader@81b81ca239c8a6dbd3a28a16b00c921300ba940e
Now supports python 2.7 as well ;)

Let me know what you think

**Comment by KurochkinVasiliy** [comment]
looks great. lets merge =)

**Comment by KurochkinVasiliy** [comment]
Done.
Thank you for your participation!
